version: '3.8'

services:
  frontend:
    build:
      context: ./client/frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REACT_APP_BACKEND_URL=http://<BACKEND_IP>:5001
    depends_on:
      - backend

  backend:
    image: backend-image # Thay bằng tên image của backend
    container_name: backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production